version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "products-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qgy2jzisam46"
s3_prefix = "products-service"
region = "us-east-1"
profile = "serverless"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
