AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CreateProduct: 
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.6
      CodeUri: src/lambda/
      Handler: create_product.handler
      TimeOut: 3
      Description: A function to create productss