AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  CreateProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/
      Handler: create_product.handler
      Runtime: python3.6
      Description: A function to create products.
